# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'itgs_ia' do
  use_frameworks!
  pod 'SideMenu'

  target 'itgs_iaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
